### ISSUE TITLE
Get-AWSCmdletName (S3) returning incorrect names, eg. Get-S3S3Bucket

### ISSUE THREAD

**Issue by fireflycons** [aws/aws-tools-for-powershell#77] opened 2019-11-23 15:42 UTC
**Expected Behavior**

`Get-AWSCmdletName -Service S3` should return correct cmdlet names

**Current Behavior**

In most of the results, the string `S3` is duplicated (some results omitted for brevity):

```
PS H:\> Get-AWSCmdletName -Service S3

CmdletName                               ServiceOperation
----------                               ----------------
Add-S3S3PublicAccessBlock                PutPublicAccessBlock
Copy-S3Object                            CopyObject
Get-S3PreSignedURL                       GetPreSignedURL
Get-S3S3ACL                              GetACL
Get-S3S3Bucket                           ListBuckets
Get-S3S3BucketAccelerateConfiguration    GetBucketAccelerateConfiguration
Get-S3S3BucketAnalyticsConfiguration     GetBucketAnalyticsConfiguration
Get-S3S3BucketAnalyticsConfigurationList ListBucketAnalyticsConfigurations
Get-S3S3BucketEncryption                 GetBucketEncryption
Get-S3S3BucketInventoryConfiguration     GetBucketInventoryConfiguration
Get-S3S3BucketInventoryConfigurationList ListBucketInventoryConfigurations
Get-S3S3BucketLocation                   GetBucketLocation
Get-S3S3BucketLogging                    GetBucketLogging
Get-S3S3BucketMetricsConfiguration       GetBucketMetricsConfiguration
Get-S3S3BucketMetricsConfigurationList   ListBucketMetricsConfigurations
Get-S3S3BucketNotification               GetBucketNotification
Get-S3S3BucketPolicy                     GetBucketPolicy
Get-S3S3BucketPolicyStatus               GetBucketPolicyStatus
Get-S3S3BucketReplication                GetBucketReplication
Get-S3S3BucketRequestPayment             GetBucketRequestPayment
```

**Possible Solution**

n/a

**Steps to Reproduce (for bugs)**

Simply run as per above

**Context**

No big deal - I use this to auto-generate a set of pester mocks to throw `NotImplementedException ` to help me catch cmdlets I may have used somewhere, but not mocked explicitly. Can work around.

May be similar for other services, I have not checked them all.

**Your Environment**

Include as many relevant details about the environment where the bug was discovered.
* Affected module (_AWSPowerShell_, _AWSPowerShell.NetCore_): Both 
* Module version as reported by `Get-AWSPowerShellVersion`: 4.0.0.0
* Operating System and version as reported by `$PSVersionTable.OS`: Microsoft Windows 10.0.18362
* PowerShell version as reported by `$PSVersionTable.PSEdition`: Core and Desktop

**Comment by fireflycons** [comment] 2019-11-23 16:02
Apologies - I see it's a duplicate of #70 .
Confirms it exists in desktop as well as core

**Comment by matteo-prosperi** [comment] 2019-11-23 21:16
Thanks for reporting this issue.
Closing as duplicate of https://github.com/aws/aws-tools-for-powershell/issues/70.
This is addressed in https://github.com/aws/aws-tools-for-powershell/pull/71 and scheduled for the upcoming release.

**Closed by matteo-prosperi** 2019-11-23 21:16 UTC
Labels: duplicate
