### ISSUE TITLE
Get-AWSPowerShellVersion Not (Entirely) Working in AWS.Tools.Common

### ISSUE THREAD

**Issue by tommymaynard** [aws/aws-tools-for-powershell#47] opened 2019-09-04 15:17 UTC
**Expected Behavior**

Based on the AWSPowerShell and AWSPowerShell.NetCore modules, the Get-AWSPowerShellVersion Cmdlet in the AWS.Tools.Common module variant is only partially working. I do recognize this module is in prerelease, but the command has worked previously. The cmdlet _is_ returning the version text: 

"_AWS Tools for PowerShell_
_Version 3.3.563.1_
_Copyright 20_...etc."

The ListServiceVersionInfo parameter, however, is failing. I _strongly_ believe that AWS should __leave it__ in its current state (not working [I’m serious -- hear me out]). Instead perhaps, throw a warning to indicate the parameter will be removed in future versions. There's more information as to why, included below. Please do read that.

**Current Behavior**

When the Get-AWSPowerShellVersion Cmdlet is used with the optional, ListServiceVersionInfo Switch parameter, the AWS Services, their "Noun Prefix," and their versions (dates) are not being returned, as they were/do in the AWSPowerShell and AWSPowerShell.NetCore modules.

**Possible Solution**

My recommended solution is here: [_Need Another AWS Change_](https://powershell.org/2019/02/need-another-aws-change/). I know, I know. I’m trying to be short and concise and I just pointed you at a blog post. It’s mostly images, however.

I'll quickly explain what my February 2019 post tried to do, so it's not required reading. Do keep in mind, however, that if we can get these changes implemented, I’ll _happily_ write a new post at [PowerShell.org](https://powershell.org) to indicate the changes, _and_ update the previously written post to point at the newest one.

Cmdlets and functions should only do one thing. Additionally, they should only return one type of object. I recommend removing the ListServiceVersionInfo parameter, except to throw a warning. The warning should indicate to use the Get-AWSService Cmdlet – the team will have to write that one. :) The new cmdlet should return the AWS Services, the Noun Prefix (_please_ remove the space in this property name), and the API Version (_please_ remove this space, as well). You’ll be fixing one command by mildly altering it (although it’s not working now) and adding a new one. Again, I would highly recommend you read my post from earlier this year.

**Steps to Reproduce (for bugs)**

Get-AWSPowerShellVersion -ListServiceVersionInfo

**Context**

Please see the above link and text in the **Possible Solution** section.

**Your Environment**

* Affected module: AWS.Tools.Common
* Module version: 3.3.563.1
* Operating System and version: Microsoft Windows 10.0.18362
* PowerShell version: Core (6.2.2 and 7.0.0-preview.3) Desktop (5.1.18362.145)

**Comment by matteo-prosperi** [comment] 2019-09-14 00:48
Hello,
thanks for your feedback.
We plan to review and restore the full functionality of Get-AWSPowerShellVersion (and Get-AWSCmdletName) before AWS.Tools reaches General Availability.

**Comment by matteo-prosperi** [comment] 2019-11-13 00:04
Hello, we have addressed this issue and it will be fixed in the next release.

**Comment by matteo-prosperi** [comment] 2019-11-22 03:13
Hello, thanks for reporting this. The issue is addressed in version 4.0 of AWS.Tools.Common.

**Closed by matteo-prosperi** 2019-11-22 03:13 UTC
Labels: enhancement, help wanted
