### ISSUE TITLE
Update-LMFunctionCode cannot update ImageUri

### ISSUE THREAD

**Issue by krymtkts** [aws/aws-tools-for-powershell#225] opened 2021-06-20 04:35 UTC
## Description

`Update-LMFunctionCode` cannot update the image URI of Lambda function because this function has a default parameter set named `'FromMemoryStream'` and `ImageUri` option doesn't have a parameter set name. 

https://github.com/aws/aws-tools-for-powershell/blob/0b04f48e74c70d7468c7d3582179d38e53708bca/modules/AWSPowerShell/Cmdlets/Lambda/Basic/Update-LMFunctionCode-Cmdlet.cs#L45

https://github.com/aws/aws-tools-for-powershell/blob/0b04f48e74c70d7468c7d3582179d38e53708bca/modules/AWSPowerShell/Cmdlets/Lambda/Basic/Update-LMFunctionCode-Cmdlet.cs#L75-L83

So we cannot update image URI using the `ImageUri` option. It is blocked by unnecessary mandatory parameter `ZipFile`. Of course the `ImageUri` option cannot use with `ZipFile` option.

```powershell
# requires input `ZipFile` parameter.
Update-LMFunctionCode -FunctionName $functionName -ImageUri $imageUri
# cmdlet Update-LMFunctionCode at command pipeline position 1
# Supply values for the following parameters:
# ZipFile[0]:

Update-LMFunctionCode -FunctionName $functionName -ImageUri $imageUri -ZipFile .\Package.zip
# Update-LMFunctionCode: Please don't provide ImageUri when updating a function with packageType Zip.
```

aws cli v2 works well in the same case.

```bash
aws lambda update-function-code --function-name ${functionName} --image-uri ${imageUri}
# we can update imageUri.
```

### Logs

none.

### Environment

* Build Version: 4.1.13.0
* OS Info: Windows 10
* Build Environment: 
* Targeted .NET Platform:  

```powershell
 $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

```powershell
PS> Get-Module AWS.Tools.Lambda

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Binary     4.1.13.0              AWS.Tools.Lambda                    {Add-LMLayerVersionPermission, Add-LMPermission, Add-LMResourceTag, Get-LMAccountSetting…}

```

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment] 2021-06-21 16:12
Similar to repro in https://github.com/aws/aws-tools-for-powershell/issues/202

**Comment by ashishdhingra** [comment] 2021-06-22 20:54
**Reproduction Steps:**
- Created a simple Lambda function using `dotnet new lambda.image.EmptyFunction`.
- Modified `Dockerfile` to below:

```
FROM public.ecr.aws/lambda/dotnet:5.0 as base

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim as build
COPY . /TestFunction

WORKDIR /TestFunction

RUN dotnet build "TestFunction.csproj" --configuration Release --output /app/build

FROM build AS publish
RUN dotnet publish "TestFunction.csproj" \\
    --configuration Release \\
    --runtime linux-x64 \\
    --self-contained false \\
    --output /app/publish \\
    -p:PublishReadyToRun=true

FROM base AS final
WORKDIR /var/task

COPY --from=publish /app/publish .
```

- Executed `docker build -t testlambdadotnet .` to build docker image.
- In AWS Console, created an ECR repository. Then clicked on View Push Commands and executed following commands one by one:
-- `aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 139480602983.dkr.ecr.us-east-2.amazonaws.com`
-- `docker build -t testlambdadotnet .`
-- `docker tag testlambdadotnet:latest 139480602983.dkr.ecr.us-east-2.amazonaws.com/testlambdadotnet:latest`
-- `docker push 139480602983.dkr.ecr.us-east-2.amazonaws.com/testlambdadotnet:latest`

- Created new IAM role arn:aws:iam::139480602983:role/testlambdaexecute-role with `AWSLambdaBasicExecutionRole` policy.
- Executed AWS CLI command to create Lambda function:
```
aws lambda create-function \
    --role arn:aws:iam::139480602983:role/testlambdaexecute-role \
    --function-name lambda-docker-dotnet \
    --package-type Image \
    --code ImageUri=139480602983.dkr.ecr.us-east-2.amazonaws.com/testlambdadotnet:latest
```

- Executing `aws lambda update-function-code --function-name "lambda-docker-dotnet" --image-uri 139480602983.dkr.ecr.us-east-2.amazonaws.com/testlambdadotnet:latest` works fine.

- However, executing `Update-LMFunctionCode -FunctionName lambda-docker-dotnet -ImageUri 139480602983.dkr.ecr.us-east-2.amazonaws.com/testlambdadotnet:latest` prompts for ZIP file parameter. This is an issue.

**Comment by coreyfournier** [comment] 2021-10-15 14:02
Any movement on this? It's affecting me. Due to ML models being so large we must use docker images to use lambda functions.

**Comment by ashishdhingra** [comment] 2022-01-27 18:43
This should be fixed in [AWS.Tools.Lambda 4.1.18.0](https://www.powershellgallery.com/packages/AWS.Tools.Lambda/4.1.18.0)

**Closed by ashishdhingra** 2022-01-27 18:43 UTC
Labels: bug, module/powershell-cmdlets, A, queued
