### ISSUE TITLE
Send-SSMCommand -DocumentName 'AWS-ConfigureAWSPackage' - error document does not support parameters

### ISSUE THREAD

**Issue by taylorchurch** [aws/aws-tools-for-powershell#275] opened 2022-06-30 20:22 UTC
### Describe the bug

Attempting to install CloudWatch on an EC2 instance works in the aws console ui and works with aws cli with parameters argument, however using PowerShell (7.2.5) (aws.tools  version 4.1.42)  Send-SSMCommand errors that the document does not support parameters. Surely the document supports parameters because if I run the Powershell code below without the parameter (or parameters, with an S) there is no package name specified so it wouldn't even know what package to install. 

![RunCommand_InstallCloudWatch_Broken](https://user-images.githubusercontent.com/73327482/176769415-cf827a1c-ef3c-49a5-a7e2-84d0c7e3d027.JPG)

Here shows that running the same command using the awscli is working with parameters flag

![RunCommand_InstallCloudWatch_WorkingAWScli](https://user-images.githubusercontent.com/73327482/176770553-47fee849-c933-4ba2-8cb4-c718a593cde0.JPG)

### Expected Behavior

Parameter(s) flag should be accepted and return data from AWS

### Current Behavior

Send-SSMCommand: document AWS-ConfigureAWSPackage does not support parameters.

### Reproduction Steps

Simply run the command included in the screenshot. This is just an attempt to install CloudWatch agent onto EC2 instance via RunCommand. 

### AWS Tools for PowerShell version used

AWS.Tools 4.1.42

### PowerShell version used

7.2.5
Core
7.2.5
Microsoft Windows 10.0.19042
Win32NT
{1.0,2.0,3.0,4.0...}
2.3
1.1.0.1
3.0

### Operating System and version

Windows 10

**Comment by ashishdhingra** [comment] 2022-07-05 15:07
Duplicate of https://github.com/aws/aws-tools-for-powershell/issues/276

**Closed by ashishdhingra** 2022-07-05 15:07 UTC
Labels: bug, needs-triage
