### ISSUE TITLE
Install/Update-AwsToolsModule with -CleanUp is removing current version of modules in PowerShell 7

### ISSUE THREAD

**Issue by mike-loux-planview** [aws/aws-tools-for-powershell#251] opened 2022-03-08 17:28 UTC
## Description

When I use `Install.AWSToolsModule` in a PowerShell 7 session to install a module (e.g. AWS.Tools.SQS) with the `-CleanUp` parameter specified (to remove old versions), it installs the module (4.1.38 at the time of this writing) and dependencies...and then immediately uninstalls the very same versions.  

**NOTE - THIS APPEARS TO WORK IN POWERSHELL 5**

## Reproduction Steps

* Open Windows Terminal to a PowerShell 7 session.
* Run `Install-AWSToolsModule AWS.Tools.SQS -Force -SkipUpdate -SkipPublisherCheck -CleanUp`
* Expected behavior - the module(s) install and can be used.
* Actual behavior - the module(s) are installed and then immediately uninstalled.  
* Example (copied right from Posh session):
```PowerShell
PS ❯ Install-AWSToolsModule AWS.Tools.SQS -Force -SkipUpdate -SkipPublisherCheck -CleanUp
Package source with Name: AWSToolsTemp added successfully.
Installing module AWS.Tools.SQS version 4.1.38
Package source with Name: AWSToolsTemp removed successfully.
Uninstalling AWS.Tools version 4.1.38
Uninstalling module AWS.Tools.SQS
Uninstalling module AWS.Tools.Common
```

So, of course attempting to use module functions at that point fails with an error similar to the following: `The term 'Get-SQSQueue' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

I even tried removing every trace of any AWS Posh module from my system and starting from scratch.  Same result.  

Also, doing Install-AWSToolsModule first without the `-CleanUp` parameter, and then doing `Update-AWSToolsModule` has the same result - the current versions are removed.  

Guessing this might be a bug with comparing versions, or the current version (which is likely stored...somewhere) is wrong?

PowerShell 5 output for comparison:
```PowerShell
PS ❯ Install-AWSToolsModule AWS.Tools.SQS -Force -SkipUpdate -SkipPublisherCheck -CleanUp
Package source with Name: AWSToolsTemp added successfully.
Installing module AWS.Tools.SQS version 4.1.38.0
Package source with Name: AWSToolsTemp removed successfully.
```

### Logs

N/A - See output above. 

### Environment

* Build Version: AWS.Tools.Installer v1.0.2.4
* OS Info: Windows 10 Pro, v20H2
* Build Environment: Windows Terminal Preview - version 1.13.10395.0 - PowerShell v7.2.1
* Targeted .NET Platform:  N/A

## Resolution
- [ ] :wave: I can/would-like-to implement a fix for this problem myself

---

This is a :bug: bug-report

**Comment by boblodgett** [comment] 2022-03-08 19:13
This sounds identical to the issue we solved 11 days ago because we had to go to the 3 part versions when trailed with a .0 in a 4 part version. That solved issue is here: https://github.com/aws/aws-tools-for-powershell/issues/248

We will need to try to reproduce this issue but can you double check you only have version 1.0.2.4 installed of AWS.Tools.Installer?

`Get-Module -ListAvailable -Name aws*`

**Comment by mike-loux-planview** [comment] 2022-03-08 19:18
Well, I had to keep working, so I have more than that installed now...

```PowerShell
PS ❯ Get-Module -ListAvailable -Name aws*

    Directory: C:\Users\mloux\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Binary     4.1.38                AWS.Tools.Common                    Core,Desk {Clear-AWSHistory, Set-AWSHistoryConfiguration, Initialize-AWSDefaultConfiguration, Clear-AWSDefaultConfiguration…}
Script     1.0.2.4               AWS.Tools.Installer                 Core,Desk {Uninstall-AWSToolsModule, Install-AWSToolsModule, Update-AWSToolsModule}
Binary     4.1.38                AWS.Tools.SQS                       Core,Desk {Add-SQSPermission, Add-SQSResourceTag, Clear-SQSQueue, Edit-SQSMessageVisibility…}
```

But I can uninstall everything from both PS Editions and re-test.  Gimme a few minutes...

**Comment by mike-loux-planview** [comment] 2022-03-08 19:33
OK.  Uninstalled All The Things™ from both PS Editions:
```PowerShell
PS ❯ $PSVersionTable.PSVersion.ToString()
7.2.1
PS ❯ Uninstall-AWSToolsModule -Force
Uninstalling AWS.Tools version 4.1.38
Uninstalling module AWS.Tools.SQS
Uninstalling module AWS.Tools.Common
PS ❯ Uninstall-Module AWS.Tools.Installer -Force
PS ❯ Get-Module -ListAvailable -Name aws*
PS ❯
```

(similar output for Posh 5)

I then closed and reopened Windows Terminal, and did the following commands...which now appear to be working.  Which is...weird.  

```PowerShell
PowerShell 7.2.1
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

Loading personal and system profiles took 1831ms.
PS ❯ Install-Module AWS.Tools.Installer -Force -SkipPublisherCheck
WARNING: The version '1.4.7' of module 'PackageManagement' is currently in use. Retry the operation after closing the applications.
PS ❯ Get-InstalledModule *aws*

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.0.2.4              AWS.Tools.Installer                 PSGallery            The AWS.Tools.Installer module makes it easier to install, update and uninstall other AWS.Tools modules (see https://www.powershellgallery.com/packages/AWS.…

PS ❯ Install-AWSToolsModule AWS.Tools.SQS -Force -SkipUpdate -SkipPublisherCheck -CleanUp
Package source with Name: AWSToolsTemp added successfully.
Installing module AWS.Tools.SQS version 4.1.38.0
Package source with Name: AWSToolsTemp removed successfully.
PS ❯ Get-InstalledModule *aws*

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
4.1.38               AWS.Tools.Common                    C:\Users\mloux\AppD… The AWS Tools for PowerShell lets developers and administrators manage their AWS services from the PowerShell scripting environment. In order to manage each…
1.0.2.4              AWS.Tools.Installer                 PSGallery            The AWS.Tools.Installer module makes it easier to install, update and uninstall other AWS.Tools modules (see https://www.powershellgallery.com/packages/AWS.…
4.1.38               AWS.Tools.SQS                       C:\Users\mloux\AppD… The SQS module of AWS Tools for PowerShell lets developers and administrators manage Amazon Simple Queue Service (SQS) from the PowerShell scripting environ…

PS ❯
```

Welp...I'm at a loss, but at least it's working for me now.  

Possible theory - I also had a couple of instances of VS code open where I was editing a script that uses the SQS module - maybe there was some cruft from those, since those Posh environments can get flaky sometimes...

**Comment by boblodgett** [comment] 2022-03-08 20:18
We have attempted to reproduce the issue but are unable to do so. My guess is an older version of the AWS.Tools.Installer was still active in your session which would certainly experience the issue. Since it is working for you now and it appears you cannot repeat the problem at this time either I am going to close this issue. 

Please reopen if you experience any further difficulties.

**Closed by boblodgett** 2022-03-08 20:18 UTC
Labels: bug, module/powershell-cmdlets
