### ISSUE TITLE
Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest.Iops issue

### ISSUE THREAD

**Issue by hsuantio** [aws/aws-tools-for-powershell#24] opened 2019-07-01 23:01 UTC
EC2 launch template created using Powershell fails to launch EC2 instance due to gp2 EBS disk IOPS value is set to default value of 0. Error message: ````"The parameter iops is not supported for gp2 volumes"````

## Expected Behavior

1. When launching an EC2 instance from a launch template, if EBS disk volume type is gp2, specified IOPS value should not be used as specified [here.](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_LaunchTemplateEbsBlockDeviceRequest.html) Otherwise, it should be possible to set ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest.Iops```` value to null.
2. If ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest.Iops```` value is null, it should return the same value retrieved using other SDKs. 

## Current Behavior
1. The ````New-EC2LaunchTemplateVersion```` cmdlet accepts either or both ````-LaunchTemplateData```` or/and ````-SourceTemplateData```` parameters for launch template data. Focusing only on ````-LaunchTemplateData```` parameter:
a. The cmdlet's ````LaunchTemplateData```` parameter accepts ````Amazon.EC2.Model.RequestLaunchTemplateData```` object class.
b. ````Amazon.EC2.Model.RequestLaunchTemplateData```` object class has an EBS disk mapping property which is a list of ````Amazon.EC2.Model.LaunchTemplateBlockDeviceMappingRequest```` object class.
c.  ````Amazon.EC2.Model.LaunchTemplateBlockDeviceMappingRequest```` object class has a Ebs disk property which is an ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest```` object class.
d. ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest```` object class' ````Iops```` property is an integer data type.

By default, when ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest```` object is created, the Iops property is set as 0 as shown below:
```
$ebs_disk = New-Object Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest
$ebs_disk
DeleteOnTermination : False
Encrypted           : False
Iops                : 0
KmsKeyId            :
SnapshotId          :
VolumeSize          : 0
VolumeType          :
```
Nullify the Iops property has no effect:
```
$ebs_disk.iops = $null                                                    
$ebs_disk                                                                                                                                  
DeleteOnTermination : False                                                 
Encrypted           : False                                                 
Iops                : 0                                                     
KmsKeyId            :                                                       
SnapshotId          :                                                       
VolumeSize          : 0                                                     
VolumeType          :     
```

Available methods:
```
$ebs_disk.iops | Get-Member
   TypeName: System.Int32

Name        MemberType Definition
----        ---------- ----------
CompareTo   Method     int CompareTo(System.Object value), int CompareTo(int value), int IComparable.CompareTo(System.Object obj), int IComparable[int].CompareTo(int other)
Equals      Method     bool Equals(System.Object obj), bool Equals(int obj), bool IEquatable[int].Equals(int other)
GetHashCode Method     int GetHashCode()
GetType     Method     type GetType()
GetTypeCode Method     System.TypeCode GetTypeCode(), System.TypeCode IConvertible.GetTypeCode()
ToBoolean   Method     bool IConvertible.ToBoolean(System.IFormatProvider provider)
ToByte      Method     byte IConvertible.ToByte(System.IFormatProvider provider)
ToChar      Method     char IConvertible.ToChar(System.IFormatProvider provider)
ToDateTime  Method     datetime IConvertible.ToDateTime(System.IFormatProvider provider)
ToDecimal   Method     decimal IConvertible.ToDecimal(System.IFormatProvider provider)
ToDouble    Method     double IConvertible.ToDouble(System.IFormatProvider provider)
ToInt16     Method     int16 IConvertible.ToInt16(System.IFormatProvider provider)
ToInt32     Method     int IConvertible.ToInt32(System.IFormatProvider provider)
ToInt64     Method     long IConvertible.ToInt64(System.IFormatProvider provider)
ToSByte     Method     sbyte IConvertible.ToSByte(System.IFormatProvider provider)
ToSingle    Method     float IConvertible.ToSingle(System.IFormatProvider provider)
ToString    Method     string ToString(), string ToString(string format), string ToString(System.IFormatProvider provider), string ToString(string format, System.IFormatProvider provider), string IFormattable.ToString(string format, Sys... ToType      Method     System.Object IConvertible.ToType(type conversionType, System.IFormatProvider provider)
ToUInt16    Method     uint16 IConvertible.ToUInt16(System.IFormatProvider provider)
ToUInt32    Method     uint32 IConvertible.ToUInt32(System.IFormatProvider provider)
ToUInt64    Method     uint64 IConvertible.ToUInt64(System.IFormatProvider provider)
```               
Failure to nullify the IOPS property when ````VolumeType```` is ````gp2```` renders the launch template unusable as launching EC2 instances using GUI or any other method failed with this error: ````"The parameter iops is not supported for gp2 volumes"````

2. If ````Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest.Iops```` is null:
a. Powershell returns 0.
b. Other SDKs, such as Python returns the correct value of null.

## Steps to Reproduce (Powershell)
1. Issue 1
````
#Create LaunchTemplateEbsBlockDeviceRequest: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateEbsBlockDeviceRequest.html
$LaunchTemplateEbsBlockDeviceRequest = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateEbsBlockDeviceRequest
$LaunchTemplateEbsBlockDeviceRequest.DeleteOnTermination = $true
$LaunchTemplateEbsBlockDeviceRequest.Iops = $null
$LaunchTemplateEbsBlockDeviceRequest.SnapshotId = "snap-0aaa4145f66e70c33" #AMI ami-0bbdf9279190cdd33 root device snapshot ID
$LaunchTemplateEbsBlockDeviceRequest.VolumeSize = 30
$LaunchTemplateEbsBlockDeviceRequest.VolumeType = "gp2" 

#Create LaunchTemplateBlockDeviceMappingRequest: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateBlockDeviceMappingRequest.html
$LaunchTemplateBlockDeviceMappingRequest = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateBlockDeviceMappingRequest
$LaunchTemplateBlockDeviceMappingRequest.Ebs = $LaunchTemplateEbsBlockDeviceRequest
$LaunchTemplateBlockDeviceMappingRequest.DeviceName = "/dev/sda1"

#Create RequestLaunchTemplateData: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/index.html?page=EC2/TEC2RequestLaunchTemplateData.html&tocid=Amazon_EC2_Model_RequestLaunchTemplateData
$RequestLaunchTemplateData = New-Object -TypeName Amazon.EC2.Model.RequestLaunchTemplateData
$RequestLaunchTemplateData.BlockDeviceMappings = $LaunchTemplateBlockDeviceMappingRequest
$RequestLaunchTemplateData.ImageId = "ami-0bbdf9279190cdd33"

#Create EC2 launch template
New-EC2LaunchTemplate -LaunchTemplateData $RequestLaunchTemplateData -LaunchTemplateName "TestIssue1"

#Create LaunchTemplateSpecification: https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/EC2/TLaunchTemplateSpecification.html
$LaunchTemplateSpec = New-Object -TypeName Amazon.EC2.Model.LaunchTemplateSpecification
$LaunchTemplateSpec.LaunchTemplateName = "TestIssue1"
$LaunchTemplateSpec.Version = 1

#Launch new EC2 instance from created launch template
New-EC2Instance -LaunchTemplate $LaunchTemplateSpec -SubnetId subnet-0924382f5e3e147df

# Exception caught
<# New-EC2Instance : The parameter iops is not supported for gp2 volumes.
At line:1 char:1
+ New-EC2Instance -LaunchTemplate $LaunchTemplateSpec -SubnetId subnet- ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...2InstanceCmdlet:NewEC2InstanceCmdlet) [New-EC2Instance], InvalidOperationException
    + FullyQualifiedErrorId : Amazon.EC2.AmazonEC2Exception,Amazon.PowerShell.Cmdlets.EC2.NewEC2InstanceCmdlet #>
````

2. Issue 2
a. Create a new version of TestIssue1 launch template using GUI or other SDKs other than .NET/Powershell. Set the gp2 EBS disk from 0 to null.
b. Retrieve the value using Powershell:
````
((Get-EC2TemplateVersion -LaunchTemplateName "TestIssue1").LaunchTemplateData.BlockDeviceMappings | Where-Object {$_.DeviceName -Match "/dev/sda1"}).Ebs

DeleteOnTermination : True                   
Encrypted           : False                  
Iops                : 0                      
KmsKeyId            :                        
SnapshotId          : snap-0a1194e6c78114ead 
VolumeSize          : 30                     
VolumeType          : gp2                    
                                             
DeleteOnTermination : True                   
Encrypted           : False                  
Iops                : 0                      
KmsKeyId            :                        
SnapshotId          : snap-0aaa4145f66e70c33 
VolumeSize          : 30                     
VolumeType          : gp2                    
````
Retrieving the same object using AWS CLI:
````
aws ec2 describe-launch-template-versions --launch-template-name "TestIssue1"   
{                                                                                 
    "LaunchTemplateVersions": [                                                   
        {                                                                         
            "LaunchTemplateId": "lt-0a0270f2a4d8a9793",                           
            "LaunchTemplateName": "TestIssue1",                                   
            "VersionNumber": 2,                                                   
            "CreateTime": "2019-07-01T11:15:20.000Z",                             
            "CreatedBy": "arn:aws:iam::752879605274:user/apiuser",                
            "DefaultVersion": false,                                              
            "LaunchTemplateData": {                                               
                "BlockDeviceMappings": [                                          
                    {                                                             
                        "DeviceName": "/dev/sda1",                                
                        "Ebs": {                                                  
                            "DeleteOnTermination": true,                          
                            "SnapshotId": "snap-0a1194e6c78114ead",               
                            "VolumeSize": 30,                                     
                            "VolumeType": "gp2"                                   
                        }                                                         
                    }                                                             
                ],                                                                
                "ImageId": "ami-0bbdf9279190cdd33"                                
            }                                                                     
        },                                                                        
        {                                                                         
            "LaunchTemplateId": "lt-0a0270f2a4d8a9793",                           
            "LaunchTemplateName": "TestIssue1",                                   
            "VersionNumber": 1,                                                   
            "CreateTime": "2019-07-01T10:48:08.000Z",                             
            "CreatedBy": "arn:aws:iam::752879605274:user/apiuser",                
            "DefaultVersion": true,                                               
            "LaunchTemplateData": {                                               
                "BlockDeviceMappings": [                                          
                    {                                                             
                        "DeviceName": "/dev/sda1",                                
                        "Ebs": {                                                  
                            "DeleteOnTermination": true,                          
                            "Iops": 0,                                            
                            "SnapshotId": "snap-0aaa4145f66e70c33",               
                            "VolumeSize": 30,                                     
                            "VolumeType": "gp2"                                   
                        }                                                         
                    }                                                             
                ],                                                                
                "ImageId": "ami-0bbdf9279190cdd33"                                
            }                                                                     
        }                                                                         
    ]                                                                             
}                                                                                 
````
Notice the same object IOPS value returned from Powershell is different from AWS CLI.

## Context
Unable to implement launch template/versions automation using Powershell. Workaround is to use other SDKs however this is not practical given the automation is based on Powershell.

**Your Environment**
Include as many relevant details about the environment where the bug was discovered.
* Affected module (AWSPowerShell or AWSPowerShell.NetCore): AWSPowershell
* Module version as reported by `Get-AWSPowerShellVersion`: 3.3.522.0
* Operating System and version as reported by `$PSVersionTable.OS`: Windows 10 (10.0.17763)
* PowerShell verions as reported by `$PSVersionTable.PSEdition`: Desktop

**Comment by matteo-prosperi** [comment] 2019-07-03 16:43
Hello,
this is a duplicate of https://github.com/aws/aws-sdk-net/issues/1331, I am closing this in favor of the other issue because this is related to the way service inputs and outputs are modeled in the AWS SDK for .NET.
I will answer there.

**Closed by matteo-prosperi** 2019-07-03 16:43 UTC
