### ISSUE TITLE
Copy-S3Object -TagSet doesn't tag

### ISSUE THREAD

**Issue by jgard** [aws/aws-tools-for-powershell#279] opened 2022-07-21 22:12 UTC
### Describe the bug

Copy-S3Object indicates it has a -TagSet parameter to tag the destination object.  It does not seem like this does anything.  Cloudtrail doesn't show the requestParameters with tags, and the resulting object isn't tagged.  Looking at the [raw API](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html), [AWSCLI](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/copy-object.html), and [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.copy_object), all require an additional parameter "tagging directive" to dictate whether tags are to be copied (merged) or replaced by the new tags.

Because Copy-S3Object is lacking that parameter, I'm guessing this is an incompletely implemented feature?

### Expected Behavior

The destination object has the tags sent with the command.

### Current Behavior

The destination object does not have the tags sent with the command.

### Reproduction Steps

```powershell
Copy-S3Object -BucketName my-bucket1 -Destinationbucket my-bucket1 -Key file1.txt -Destinationkey file2.txt -TagSet @{Key='testtag';Value='testvalue'}
```

### AWS Tools for PowerShell version used

```
Both:
AWSPowerShell    4.1.41
AWS.Tools.S3     4.1.104
```

### PowerShell version used

Both:
```
Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
```
Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Operating System and version

Windows 10 and Windows Server 2019

**Comment by ashishdhingra** [comment] 2022-07-26 23:11
Per documentation for S3 [CopyObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html) service API operation, the [x-amz-tagging](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestSyntax) is the tag-set for the object destination object and this value **must be used** in conjunction with the `TaggingDirective`. The [x-amz-tagging-directive](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html#API_CopyObject_RequestSyntax) specifies whether the object tag-set are copied from the source object or replaced with tag-set provided in the request.

Need to check if in the underlying AWS SDK for .NET, the tagging directive is set or not when specifying tags.

**Comment by ashishdhingra** [comment] 2022-07-27 17:53
Reproducible using `Copy-S3Object -BucketName testbucket -Destinationbucket testbucket -Key src.txt -Destinationkey src-copy.txt -TagSet @{Key='testtag';Value='testvalue'}`.

**Root cause:** `TagSet` parameter passed by user is not consumed and passed down the line to `CmdletContext` [here](https://github.com/aws/aws-tools-for-powershell/blob/ba614cea17d3f062dd0f6fca7c8a3b7a8ace2477/modules/AWSPowerShell/Cmdlets/S3/Advanced/Copy-S3Object-Cmdlet.cs#L470).

**Comment by ashishdhingra** [comment] 2022-08-04 00:02
This should be fixed in [AWS.Tools.S3 4.1.140](https://www.powershellgallery.com/packages/AWS.Tools.S3/4.1.140).

**Closed by ashishdhingra** 2022-08-04 00:02 UTC
Labels: bug, module/powershell-cmdlets, A, queued
