### ISSUE TITLE
Autopagination not working

### ISSUE THREAD

**Issue by lgaudreau** [aws/aws-tools-for-powershell#147] opened 2020-04-16 17:40 UTC
While running a command like 'get-ec2snapshot' in a region where there are more than 1000 snapshots, the command fails with 

`Get-EC2Snapshot: You have exceeded the output limit for an unpaginated response. Retry your request using pagination parameters.`

Running with -maxresults returns a warning that the command is deprecated, but the solution presented (to pipe the results to Select-Object -First ##) also fails since it requires returning all objects first.

This was not happening in AWSPowerShell 3.3.563.1 at least.

**Comment by matteo-prosperi** [comment] 2020-04-16 20:01
I think this can be fixed by setting a default value of `1000` for `-MaxResult`. I will mark this as a bug.

I believe previous versions of the module are similarly affected, they would just return a partial output without complaining. You should be able to restore this behavior by passing `-MaxResult 1000` and ignoring the warning.

Information for the implementer of the fix: AWS.Tools will have a different behavior and should be tested as well.

**Comment by lgaudreau** [comment] 2020-05-22 16:46
I've installed AWS.Tools version 4.0.5.0 and have run into the following behaviour:

With 15,000 snapshots in the account, running 'Get-EC2Snapshot -Owner self' returns the same error:
`Get-EC2Snapshot: You have exceeded the output limit for an unpaginated response. Retry your request using pagination parameters.`
Using -MaxResult 1000 returns the first 1000, but setting -NextToken is not working as expected either - the second run only returns 467 items, not another 1000.

**Comment by ashishdhingra** [comment] 2020-10-14 19:26
Hi @lgaudreau,

Good afternoon.

I was going through the issue backlog and came across the issue. The `-NextToken` appears to work fine for me:

```PowerShell
Get-EC2Snapshot -MaxResult 10 -NextToken $null 
Get-EC2Snapshot -MaxResult 10 -NextToken $AWSHistory.LastServiceResponse.NextToken
```

**Output of `Get-InstalledModule | Select Version,Name`**
```
Version Name
------- ----
4.1.2.0 AWS.Tools.EC2
4.1.2.0 AWS.Tools.IdentityManagement
4.1.2.0 AWS.Tools.Glacier
4.1.2.0 AWS.Tools.S3
4.1.2.0 AWS.Tools.SQS
4.1.2.0 AWS.Tools.Common
4.1.2.0 AWS.Tools.SimpleNotificationService
4.1.2.0 AWSPowerShell
1.0.2.0 AWS.Tools.Installer
2.0.0.0 AWSLambdaPSCore
4.1.2.0 AWSPowerShell.NetCore
```

**Output of `Get-AWSPowerShellVersion`**
```
AWS Tools for Windows PowerShell
Version 3.3.119.0
Copyright 2012-2017 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.3.17.0
Copyright 2009-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://aws.amazon.com/releasenotes/PowerShell

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License
[http://logging.apache.org/log4net/license.html]
```

Please try with the latest version of Powershell Tools/Modules and confirm if the issue is resolved.

Thanks,
Ashish

**Comment by lgaudreau** [comment] 2020-10-14 20:16
Hi Ashish,

Using -NextToken works correctly as a workaround.  Auto-pagination is still not working using the latest version:

Output of Get-EC2Snapshot -Owner self
Get-EC2Snapshot: You have exceeded the output limit for an unpaginated response. Retry your request using pagination parameters.

Output of Get-InstalledModule | Select Version,Name
Version Name
------- ----
4.1.2.0 AWS.Tools.Common
4.1.2.0 AWS.Tools.EC2
1.0.2.0 AWS.Tools.Installer
4.1.2.0 AWS.Tools.RDS
4.1.2.0 AWS.Tools.Route53
4.1.2.0 AWS.Tools.S3
4.1.2.0 AWS.Tools.WAFV2
4.1.2.0 AWS.Tools.WorkDocs
4.1.2.0 AWS.Tools.WorkSpaces

Output of Get-AWSPowerShellVersion
AWS Tools for PowerShell
Version 4.1.2.0
Copyright 2012-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.

Amazon Web Services SDK for .NET
Core Runtime Version 3.5.1.23
Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.

Release notes: https://github.com/aws/aws-tools-for-powershell/blob/master/CHANGELOG.md

This software includes third party software subject to the following copyrights:
- Logging from log4net, Apache License
[http://logging.apache.org/log4net/license.html]

Thanks,

Lincoln
________________________________

**Comment by ashishdhingra** [comment] 2020-10-15 17:52
Hi @lgaudreau,

Thanks for your reply. I think we already have a feature request https://github.com/aws/aws-tools-for-powershell/issues/117 to support auto-pagination for `AWS.Tools.*`. Please confirm if we close this issue in favor of the other feature request.

Thanks,
Ashish

**Comment by lgaudreau** [comment] 2020-10-15 23:36
Thank Ashish,

That's fine, yes!  This issue can be closed with the feature request open.

Lincoln
________________________________

**Closed** 2020-10-15 23:37 UTC
Labels: bug, module/powershell-cmdlets
